/// AUTOMATICALLY GENERATED
/// DO NOT MODIFY

#pragma once

#include "expand.hpp"
#include "args_count.hpp"

#define OPP_FOR_EACH(f, ...) \
    OPP_CAT(OPP_FOR_EACH, OPP_N(__VA_ARGS__))(f, __VA_ARGS__)

#define OPP_FOR_EACH1(f, x) f(x)

#define OPP_FOR_EACH100(f, x, ...) f(x) OPP_FOR_EACH99(f, __VA_ARGS__)
#define OPP_FOR_EACH99(f, x, ...) f(x) OPP_FOR_EACH98(f, __VA_ARGS__)
#define OPP_FOR_EACH98(f, x, ...) f(x) OPP_FOR_EACH97(f, __VA_ARGS__)
#define OPP_FOR_EACH97(f, x, ...) f(x) OPP_FOR_EACH96(f, __VA_ARGS__)
#define OPP_FOR_EACH96(f, x, ...) f(x) OPP_FOR_EACH95(f, __VA_ARGS__)
#define OPP_FOR_EACH95(f, x, ...) f(x) OPP_FOR_EACH94(f, __VA_ARGS__)
#define OPP_FOR_EACH94(f, x, ...) f(x) OPP_FOR_EACH93(f, __VA_ARGS__)
#define OPP_FOR_EACH93(f, x, ...) f(x) OPP_FOR_EACH92(f, __VA_ARGS__)
#define OPP_FOR_EACH92(f, x, ...) f(x) OPP_FOR_EACH91(f, __VA_ARGS__)
#define OPP_FOR_EACH91(f, x, ...) f(x) OPP_FOR_EACH90(f, __VA_ARGS__)
#define OPP_FOR_EACH90(f, x, ...) f(x) OPP_FOR_EACH89(f, __VA_ARGS__)
#define OPP_FOR_EACH89(f, x, ...) f(x) OPP_FOR_EACH88(f, __VA_ARGS__)
#define OPP_FOR_EACH88(f, x, ...) f(x) OPP_FOR_EACH87(f, __VA_ARGS__)
#define OPP_FOR_EACH87(f, x, ...) f(x) OPP_FOR_EACH86(f, __VA_ARGS__)
#define OPP_FOR_EACH86(f, x, ...) f(x) OPP_FOR_EACH85(f, __VA_ARGS__)
#define OPP_FOR_EACH85(f, x, ...) f(x) OPP_FOR_EACH84(f, __VA_ARGS__)
#define OPP_FOR_EACH84(f, x, ...) f(x) OPP_FOR_EACH83(f, __VA_ARGS__)
#define OPP_FOR_EACH83(f, x, ...) f(x) OPP_FOR_EACH82(f, __VA_ARGS__)
#define OPP_FOR_EACH82(f, x, ...) f(x) OPP_FOR_EACH81(f, __VA_ARGS__)
#define OPP_FOR_EACH81(f, x, ...) f(x) OPP_FOR_EACH80(f, __VA_ARGS__)
#define OPP_FOR_EACH80(f, x, ...) f(x) OPP_FOR_EACH79(f, __VA_ARGS__)
#define OPP_FOR_EACH79(f, x, ...) f(x) OPP_FOR_EACH78(f, __VA_ARGS__)
#define OPP_FOR_EACH78(f, x, ...) f(x) OPP_FOR_EACH77(f, __VA_ARGS__)
#define OPP_FOR_EACH77(f, x, ...) f(x) OPP_FOR_EACH76(f, __VA_ARGS__)
#define OPP_FOR_EACH76(f, x, ...) f(x) OPP_FOR_EACH75(f, __VA_ARGS__)
#define OPP_FOR_EACH75(f, x, ...) f(x) OPP_FOR_EACH74(f, __VA_ARGS__)
#define OPP_FOR_EACH74(f, x, ...) f(x) OPP_FOR_EACH73(f, __VA_ARGS__)
#define OPP_FOR_EACH73(f, x, ...) f(x) OPP_FOR_EACH72(f, __VA_ARGS__)
#define OPP_FOR_EACH72(f, x, ...) f(x) OPP_FOR_EACH71(f, __VA_ARGS__)
#define OPP_FOR_EACH71(f, x, ...) f(x) OPP_FOR_EACH70(f, __VA_ARGS__)
#define OPP_FOR_EACH70(f, x, ...) f(x) OPP_FOR_EACH69(f, __VA_ARGS__)
#define OPP_FOR_EACH69(f, x, ...) f(x) OPP_FOR_EACH68(f, __VA_ARGS__)
#define OPP_FOR_EACH68(f, x, ...) f(x) OPP_FOR_EACH67(f, __VA_ARGS__)
#define OPP_FOR_EACH67(f, x, ...) f(x) OPP_FOR_EACH66(f, __VA_ARGS__)
#define OPP_FOR_EACH66(f, x, ...) f(x) OPP_FOR_EACH65(f, __VA_ARGS__)
#define OPP_FOR_EACH65(f, x, ...) f(x) OPP_FOR_EACH64(f, __VA_ARGS__)
#define OPP_FOR_EACH64(f, x, ...) f(x) OPP_FOR_EACH63(f, __VA_ARGS__)
#define OPP_FOR_EACH63(f, x, ...) f(x) OPP_FOR_EACH62(f, __VA_ARGS__)
#define OPP_FOR_EACH62(f, x, ...) f(x) OPP_FOR_EACH61(f, __VA_ARGS__)
#define OPP_FOR_EACH61(f, x, ...) f(x) OPP_FOR_EACH60(f, __VA_ARGS__)
#define OPP_FOR_EACH60(f, x, ...) f(x) OPP_FOR_EACH59(f, __VA_ARGS__)
#define OPP_FOR_EACH59(f, x, ...) f(x) OPP_FOR_EACH58(f, __VA_ARGS__)
#define OPP_FOR_EACH58(f, x, ...) f(x) OPP_FOR_EACH57(f, __VA_ARGS__)
#define OPP_FOR_EACH57(f, x, ...) f(x) OPP_FOR_EACH56(f, __VA_ARGS__)
#define OPP_FOR_EACH56(f, x, ...) f(x) OPP_FOR_EACH55(f, __VA_ARGS__)
#define OPP_FOR_EACH55(f, x, ...) f(x) OPP_FOR_EACH54(f, __VA_ARGS__)
#define OPP_FOR_EACH54(f, x, ...) f(x) OPP_FOR_EACH53(f, __VA_ARGS__)
#define OPP_FOR_EACH53(f, x, ...) f(x) OPP_FOR_EACH52(f, __VA_ARGS__)
#define OPP_FOR_EACH52(f, x, ...) f(x) OPP_FOR_EACH51(f, __VA_ARGS__)
#define OPP_FOR_EACH51(f, x, ...) f(x) OPP_FOR_EACH50(f, __VA_ARGS__)
#define OPP_FOR_EACH50(f, x, ...) f(x) OPP_FOR_EACH49(f, __VA_ARGS__)
#define OPP_FOR_EACH49(f, x, ...) f(x) OPP_FOR_EACH48(f, __VA_ARGS__)
#define OPP_FOR_EACH48(f, x, ...) f(x) OPP_FOR_EACH47(f, __VA_ARGS__)
#define OPP_FOR_EACH47(f, x, ...) f(x) OPP_FOR_EACH46(f, __VA_ARGS__)
#define OPP_FOR_EACH46(f, x, ...) f(x) OPP_FOR_EACH45(f, __VA_ARGS__)
#define OPP_FOR_EACH45(f, x, ...) f(x) OPP_FOR_EACH44(f, __VA_ARGS__)
#define OPP_FOR_EACH44(f, x, ...) f(x) OPP_FOR_EACH43(f, __VA_ARGS__)
#define OPP_FOR_EACH43(f, x, ...) f(x) OPP_FOR_EACH42(f, __VA_ARGS__)
#define OPP_FOR_EACH42(f, x, ...) f(x) OPP_FOR_EACH41(f, __VA_ARGS__)
#define OPP_FOR_EACH41(f, x, ...) f(x) OPP_FOR_EACH40(f, __VA_ARGS__)
#define OPP_FOR_EACH40(f, x, ...) f(x) OPP_FOR_EACH39(f, __VA_ARGS__)
#define OPP_FOR_EACH39(f, x, ...) f(x) OPP_FOR_EACH38(f, __VA_ARGS__)
#define OPP_FOR_EACH38(f, x, ...) f(x) OPP_FOR_EACH37(f, __VA_ARGS__)
#define OPP_FOR_EACH37(f, x, ...) f(x) OPP_FOR_EACH36(f, __VA_ARGS__)
#define OPP_FOR_EACH36(f, x, ...) f(x) OPP_FOR_EACH35(f, __VA_ARGS__)
#define OPP_FOR_EACH35(f, x, ...) f(x) OPP_FOR_EACH34(f, __VA_ARGS__)
#define OPP_FOR_EACH34(f, x, ...) f(x) OPP_FOR_EACH33(f, __VA_ARGS__)
#define OPP_FOR_EACH33(f, x, ...) f(x) OPP_FOR_EACH32(f, __VA_ARGS__)
#define OPP_FOR_EACH32(f, x, ...) f(x) OPP_FOR_EACH31(f, __VA_ARGS__)
#define OPP_FOR_EACH31(f, x, ...) f(x) OPP_FOR_EACH30(f, __VA_ARGS__)
#define OPP_FOR_EACH30(f, x, ...) f(x) OPP_FOR_EACH29(f, __VA_ARGS__)
#define OPP_FOR_EACH29(f, x, ...) f(x) OPP_FOR_EACH28(f, __VA_ARGS__)
#define OPP_FOR_EACH28(f, x, ...) f(x) OPP_FOR_EACH27(f, __VA_ARGS__)
#define OPP_FOR_EACH27(f, x, ...) f(x) OPP_FOR_EACH26(f, __VA_ARGS__)
#define OPP_FOR_EACH26(f, x, ...) f(x) OPP_FOR_EACH25(f, __VA_ARGS__)
#define OPP_FOR_EACH25(f, x, ...) f(x) OPP_FOR_EACH24(f, __VA_ARGS__)
#define OPP_FOR_EACH24(f, x, ...) f(x) OPP_FOR_EACH23(f, __VA_ARGS__)
#define OPP_FOR_EACH23(f, x, ...) f(x) OPP_FOR_EACH22(f, __VA_ARGS__)
#define OPP_FOR_EACH22(f, x, ...) f(x) OPP_FOR_EACH21(f, __VA_ARGS__)
#define OPP_FOR_EACH21(f, x, ...) f(x) OPP_FOR_EACH20(f, __VA_ARGS__)
#define OPP_FOR_EACH20(f, x, ...) f(x) OPP_FOR_EACH19(f, __VA_ARGS__)
#define OPP_FOR_EACH19(f, x, ...) f(x) OPP_FOR_EACH18(f, __VA_ARGS__)
#define OPP_FOR_EACH18(f, x, ...) f(x) OPP_FOR_EACH17(f, __VA_ARGS__)
#define OPP_FOR_EACH17(f, x, ...) f(x) OPP_FOR_EACH16(f, __VA_ARGS__)
#define OPP_FOR_EACH16(f, x, ...) f(x) OPP_FOR_EACH15(f, __VA_ARGS__)
#define OPP_FOR_EACH15(f, x, ...) f(x) OPP_FOR_EACH14(f, __VA_ARGS__)
#define OPP_FOR_EACH14(f, x, ...) f(x) OPP_FOR_EACH13(f, __VA_ARGS__)
#define OPP_FOR_EACH13(f, x, ...) f(x) OPP_FOR_EACH12(f, __VA_ARGS__)
#define OPP_FOR_EACH12(f, x, ...) f(x) OPP_FOR_EACH11(f, __VA_ARGS__)
#define OPP_FOR_EACH11(f, x, ...) f(x) OPP_FOR_EACH10(f, __VA_ARGS__)
#define OPP_FOR_EACH10(f, x, ...) f(x) OPP_FOR_EACH9(f, __VA_ARGS__)
#define OPP_FOR_EACH9(f, x, ...) f(x) OPP_FOR_EACH8(f, __VA_ARGS__)
#define OPP_FOR_EACH8(f, x, ...) f(x) OPP_FOR_EACH7(f, __VA_ARGS__)
#define OPP_FOR_EACH7(f, x, ...) f(x) OPP_FOR_EACH6(f, __VA_ARGS__)
#define OPP_FOR_EACH6(f, x, ...) f(x) OPP_FOR_EACH5(f, __VA_ARGS__)
#define OPP_FOR_EACH5(f, x, ...) f(x) OPP_FOR_EACH4(f, __VA_ARGS__)
#define OPP_FOR_EACH4(f, x, ...) f(x) OPP_FOR_EACH3(f, __VA_ARGS__)
#define OPP_FOR_EACH3(f, x, ...) f(x) OPP_FOR_EACH2(f, __VA_ARGS__)
#define OPP_FOR_EACH2(f, x, ...) f(x) OPP_FOR_EACH1(f, __VA_ARGS__)
